services:
    threedi.topicshierarchy.listener:
        class: threedi\topicshierarchy\event\main_listener
        arguments:
            - '@language'
        tags:
            - { name: event.listener }
